/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blogspot_jesfre_calculadora_InterfazNativa */

#ifndef _Included_com_blogspot_jesfre_calculadora_InterfazNativa
#define _Included_com_blogspot_jesfre_calculadora_InterfazNativa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    sumar
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_sumar
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    restar
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_restar
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    dividir
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_dividir
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    multiplicar
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_multiplicar
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    cambioSigno
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_cambioSigno
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    seno
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_seno
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    coseno
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_coseno
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    tangente
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_tangente
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    x_y
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_x_1y
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    x_3
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_x_13
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    x_2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_x_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    log
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_log
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    negar
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_negar
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    pi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_pi
  (JNIEnv *, jobject);

/*
 * Class:     com_blogspot_jesfre_calculadora_InterfazNativa
 * Method:    uno_x
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_blogspot_jesfre_calculadora_InterfazNativa_uno_1x
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
